### ISSUE TITLE
error: Insufficient funds when creating a sell

### ISSUE THREAD

**Issue by chapolito** [chapolito/gotrader#5]
I'm seeing `error: Insufficient funds` for when trying to create sells after a buy. Since I haven't been keeping an ETH balance there are two possible explanations:

1. This is related to partial fills and the full amount isn't bought yet, so there isn't enough to be sold. I only see a single buy matching it though, so unsure if this correct.
2. The transaction has not settled and the funds simply are not available yet. Things are moving too fast?

Short term solution: keep some funds available in ETH always.

**Comment by ARolek** [comment]
sounds like you're broke
